# Generated by Django 4.2.2 on 2023-06-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0003_alter_teachermodel_tchr_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college_management_app.coursemodel'),
        ),
    ]
