# Generated by Django 4.2.2 on 2023-06-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0005_teachermodel_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_first_name', models.CharField(max_length=255)),
                ('Stu_last_name', models.CharField(max_length=255)),
                ('Stu_age', models.IntegerField()),
                ('Stu_address', models.CharField(max_length=255)),
                ('Stu_gender', models.CharField(max_length=10)),
                ('Stu_phone', models.IntegerField()),
                ('Stu_email', models.CharField(max_length=50)),
                ('Stu_image', models.ImageField(null=True, upload_to='image/')),
                ('Stu_joining_date', models.DateField(auto_now_add=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college_management_app.coursemodel')),
            ],
        ),
    ]
